/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Ventana.java
 *
 * Created on 1/12/2023, 01:28:49 PM
 */
package guibarra;

import java.awt.Color;

/**
 *
 * @author sala11
 */
public class Ventana extends javax.swing.JFrame {

    /** Creates new form Ventana */
    public Ventana() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        COLOR = new javax.swing.JLabel();
        Rojo = new javax.swing.JScrollBar();
        Verde = new javax.swing.JScrollBar();
        Azul = new javax.swing.JScrollBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(4, 0));

        COLOR.setFont(new java.awt.Font("Sylfaen", 0, 19)); // NOI18N
        COLOR.setForeground(new java.awt.Color(255, 255, 102));
        COLOR.setText("Color");
        COLOR.setOpaque(true);
        getContentPane().add(COLOR);

        Rojo.setBackground(new java.awt.Color(240, 240, 240));
        Rojo.setMaximum(255);
        Rojo.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        Rojo.setVisibleAmount(0);
        Rojo.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        Rojo.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                RojoAdjustmentValueChanged(evt);
            }
        });
        getContentPane().add(Rojo);

        Verde.setBackground(new java.awt.Color(240, 240, 240));
        Verde.setMaximum(255);
        Verde.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        Verde.setVisibleAmount(0);
        Verde.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                VerdeAdjustmentValueChanged(evt);
            }
        });
        getContentPane().add(Verde);

        Azul.setBackground(new java.awt.Color(240, 240, 240));
        Azul.setMaximum(255);
        Azul.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        Azul.setVisibleAmount(0);
        Azul.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                AzulAdjustmentValueChanged(evt);
            }
        });
        getContentPane().add(Azul);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void RojoAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_RojoAdjustmentValueChanged
// TODO add your handling code here:
    r=Rojo.getValue();
    update();
//    setTitle("ROJO");
}//GEN-LAST:event_RojoAdjustmentValueChanged

private void VerdeAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_VerdeAdjustmentValueChanged
// TODO add your handling code here:
    g=Verde.getValue();
    update();
//    setTitle("VERDE");
}//GEN-LAST:event_VerdeAdjustmentValueChanged

private void AzulAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_AzulAdjustmentValueChanged
// TODO add your handling code here:
    b=Azul.getValue();
    update();
//    setTitle("AZUL");
}//GEN-LAST:event_AzulAdjustmentValueChanged

private void update(){
    COLOR.setBackground(new Color(r,g,b));
    setTitle("Rojo:"+r+" Verde:"+g+" Azul:"+b);
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    
    int r, g, b;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollBar Azul;
    private javax.swing.JLabel COLOR;
    private javax.swing.JScrollBar Rojo;
    private javax.swing.JScrollBar Verde;
    // End of variables declaration//GEN-END:variables
}
